SHELL = /bin/sh

.SUFFIXES:
.SUFFIXES: .c .o .P

vpath %.o
vpath %.o $(OBJDIR)

vpath %.P
vpath %.P $(DEPDIR)

TBOBJS = tbgen.o tbgenp.o permute.o compress.o huffman.o threads.o lz4.o tbver.o tbverp.o decompress.o checksum.o city-c.o tbcheck.o util.o
GENTBOBJS = tbgen.o permute.o compress.o huffman.o threads.o lz4.o checksum.o city-c.o util.o
GENTBPOBJS = tbgenp.o permute.o compress.o huffman.o threads.o lz4.o checksum.o city-c.o util.o
VERTBOBJS = tbver.o decompress.o threads.o checksum.o city-c.o util.o
VERTBPOBJS = tbverp.o decompress.o threads.o checksum.o city-c.o util.o
DECOMPOBJS = tbdecompress.o decompress.o decompress-piece.o threads.o util-decomp.o
DECOMPFLAGS = $(filter-out -DUSE_ZSTD -DZSTD_LEVEL=%,$(FLAGS))
DECOMPDEPS = $(filter-out $(DEPDIR)/util-decomp.P,$(DECOMPOBJS:%.o=$(DEPDIR)/%.P))

TBCHECKOBJS = tbcheck.o threads.o checksum.o city-c.o lz4.o util.o

CFILES = $(filter $(wildcard *.c), $(OBJS:%.o=%.c))

include $(CFILES:%.c=$(DEPDIR)/%.P)
ifeq ($(MAKECMDGOALS),tbdecompress)
include $(DECOMPDEPS)
else
include $(TBOBJS:%.o=$(DEPDIR)/%.P)
endif

$(NAME): $(OBJS) # $(OBJS:%=$(OBJDIR)/%)
	$(CC) $(CFLAGS) -o $(NAME) $(OBJS:%=$(OBJDIR)/%)

%.o $(OBJDIR)/%.o: %.c
	@mkdir -p $(OBJDIR)
	$(CC) $(CFLAGS) -c $*.c $(FLAGS) -o $(OBJDIR)/$*.o

$(DEPDIR)/%.P: %.c
	@mkdir -p $(DEPDIR)
	$(SHELL) -ec '$(CC) -M $(FLAGS) $*.c | sed s/$*\.o/$*\.o\ $*\.P/ >$@'

$(DECOMPDEPS): $(DEPDIR)/%.P: %.c
	@mkdir -p $(DEPDIR)
	$(SHELL) -ec '$(CC) -M $(DECOMPFLAGS) $*.c | sed s/$*\.o/$*\.o\ $*\.P/ >$@'

$(OBJDIR)/util-decomp.o: util.c
	@mkdir -p $(OBJDIR)
	$(CC) $(CFLAGS) -c util.c $(DECOMPFLAGS) -DDECOMPRESSION_ONLY -o $@

$(CLEAN):
	rm -f $(TBOBJS:%=$(OBJDIR)/%) $(DECOMPOBJS:%=$(OBJDIR)/%)

$(GENTBNAME): $(GENTBOBJS)
	$(CC) $(CFLAGS) -o $(GENTBNAME) $(GENTBOBJS:%=$(OBJDIR)/%) $(LDFLAGS)

$(GENTBPNAME): $(GENTBPOBJS)
	$(CC) $(CFLAGS) -o $(GENTBPNAME) $(GENTBPOBJS:%=$(OBJDIR)/%) $(LDFLAGS)

$(VERTBNAME): $(VERTBOBJS)
	$(CC) $(CFLAGS) -o $(VERTBNAME) $(VERTBOBJS:%=$(OBJDIR)/%) $(LDFLAGS)

$(VERTBPNAME): $(VERTBPOBJS)
	$(CC) $(CFLAGS) -o $(VERTBPNAME) $(VERTBPOBJS:%=$(OBJDIR)/%) $(LDFLAGS)

$(DECOMPNAME): FLAGS := $(DECOMPFLAGS)
$(DECOMPNAME): $(DECOMPOBJS)
	$(CC) $(CFLAGS) -o $(DECOMPNAME) $(DECOMPOBJS:%=$(OBJDIR)/%)

tbcheck: $(TBCHECKOBJS)
	$(CC) $(CFLAGS) -o tbcheck $(TBCHECKOBJS:%=$(OBJDIR)/%)
